# Generated by Django 4.2.7 on 2024-01-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.orderitem'),
            preserve_default=False,
        ),
    ]
