# Generated by Django 4.2.7 on 2024-01-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_orderitem_image_orderitem_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(default=1, upload_to='cartoon_images'),
            preserve_default=False,
        ),
    ]
