# Generated by Django 4.2.7 on 2024-01-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_orderitem_first_name_orderitem_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
