# Generated by Django 4.2.7 on 2023-11-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
