# Generated by Django 4.2.7 on 2023-12-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0004_cartoonimageuserlike_cartoonimageuserfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseimage',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portrait.frame'),
        ),
        migrations.AddField(
            model_name='purchaseimage',
            name='is_frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseimage',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
