# Generated by Django 4.2.7 on 2023-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0005_purchaseimage_frame_purchaseimage_is_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseimage',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
