# Generated by Django 4.2.7 on 2023-12-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0006_purchaseimage_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseimage',
            name='custome_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portrait.customimage'),
        ),
        migrations.AddField(
            model_name='purchaseimage',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
